### ISSUE TITLE
Doesn't run the command in Win10 properly

### ISSUE THREAD

**Issue by Tekunalogy** [bmpenuelas/systemverilog-formatter-vscode#13]
I believe the issue is with the file path not being parsed correctly (since my username has a space in it). The command works fine if I execute it myself in the command line.

![image](https://user-images.githubusercontent.com/16601274/166776016-3645a2b7-7752-4bb8-901e-b4820d7af6c6.png)

**Comment by bmpenuelas** [comment]
Hi! I have published a new version that quotes the path to avoid problems for those with spaces in the path. Can you please try out v2.16.2?

**Comment by Tekunalogy** [comment]
The extension works flawlessly now. Thank you!
