### ISSUE TITLE
SystemVerilog Formatter - Format this file failed

### ISSUE THREAD

**Issue by ARC-MX** [bmpenuelas/systemverilog-formatter-vscode#14]
![image](https://user-images.githubusercontent.com/34829404/167295704-ed6bab5d-11c0-4329-af8e-57f519790ebc.png)

**Comment by Reset816** [comment]
got same error

**Comment by Reset816** [comment]
> got same error

on 2.16.0 and 2.16.1

**Comment by ARC-MX** [comment]
> 

所以你现在也是不能用吗

**Comment by Reset816** [comment]
> 

yes

**Comment by bmpenuelas** [comment]
Hi, I have just published v2.16.2 to fix a problem with some paths that need to be quoted. Can you try this one and let me know if it still fails? Perhaps uninstall and install from scratch.

**Comment by Reset816** [comment]
> Hi, I have just published v2.16.2 to fix a problem with some paths that need to be quoted. Can you try this one and let me know if it still fails? Perhaps uninstall and install from scratch.

I'm still getting same error with v2.16.2
![image](https://user-images.githubusercontent.com/40438607/168193359-e8b85c8d-36c5-47be-89e0-983d0b75d3c5.png)

**Comment by Reset816** [comment]
> > Hi, I have just published v2.16.2 to fix a problem with some paths that need to be quoted. Can you try this one and let me know if it still fails? Perhaps uninstall and install from scratch.
> 
> I'm still getting same error with v2.16.2 ![image](https://user-images.githubusercontent.com/40438607/168193359-e8b85c8d-36c5-47be-89e0-983d0b75d3c5.png)

VSCode 1.67.1 and Windows 11 22000.652. And the paths do not contain spaces, which are all English characters

**Comment by Reset816** [comment]
> Hi, I have just published v2.16.2 to fix a problem with some paths that need to be quoted. Can you try this one and let me know if it still fails? Perhaps uninstall and install from scratch.

Is there any way to get log and provide more information for you?

**Comment by ARC-MX** [comment]
问题仍然会出现，好像是当我重新reload window 后就出现问题了

**Comment by bmpenuelas** [comment]
Hello, I have been trying to figure out what could be failing for you guys, since it works all right for most people. 

I've published v2.16.3, can you please try and see if it is solved with this patch? (maybe try a clean install). If it still fails please let me know. 

(in case of failure with the latest version, you can click `Help > Toggle Developer Tools`, go to the `Console` tab, and see if you get any error messages there when it fails)

**Comment by Reset816** [comment]
> Hello, I have been trying to figure out what could be failing for you guys, since it works all right for most people.
> 
> I've published v2.16.3, can you please try and see if it is solved with this patch? (maybe try a clean install). If it still fails please let me know.
> 
> (in case of failure with the latest version, you can click `Help > Toggle Developer Tools`, go to the `Console` tab, and see if you get any error messages there when it fails)

It works great now.
Thank you.

**Comment by bmpenuelas** [comment]
Happy to hear that! Do not hesitate to let me know if you encounter any other issues in the future!
