### ISSUE TITLE
system error (spawnSync /bin/sh EPIPE)

### ISSUE THREAD

**Issue by david-shmailov** [bmpenuelas/systemverilog-formatter-vscode#22]
I've installed the plugin, using CentOS 7 in the configuration as this is my OS, whenever i try to format a file or selection i get this error:
system error (spawnSync /bin/sh EPIPE)

**Comment by bmpenuelas** [comment]
That looks like the spawned process either terminated unexpectedly, or there was too much data and the buffer was filled. Does this happen with small files too? You could try using the "none" setting and providing a path to some other binary just to see if you get a different message.

**Comment by david-shmailov** [comment]
EDIT:
I had to add executable permission to the binary of CentOS7 formatter in the plugin directory, and after i did, it works without displaying an error.
Tested it on a large file seems to work fine thanks!

**Comment by bmpenuelas** [comment]
Happy to hear that, thanks for the update!
