### ISSUE TITLE
"CentOS-7" option missing

### ISSUE THREAD

**Issue by leobel96** [bmpenuelas/systemverilog-formatter-vscode#7]
"CentOS-7" is missing as possible option

**Comment by bmpenuelas** [comment]
Hi, I have uploaded a new version, including the CentOS-7 version. Could you please try it and let me know if it works? Thanks for the heads-up!

**Comment by bmpenuelas** [comment]
Closing as CentOS-7, and some other legacy builds, have been included as archived versions that can also be selected in the config. 

If you find any other build that was supported at some point, and is not present in the latest releases, please open a new issue.
