### ISSUE TITLE
"Windows" is missing as possible option

### ISSUE THREAD

**Issue by garanovich** [bmpenuelas/systemverilog-formatter-vscode#8]
verible now have windows builds
https://github.com/chipsalliance/verible/releases

**Comment by bmpenuelas** [comment]
Hi, I have uploaded a new version, including the Windows build among other things. Could you please try it and let me know if it works? Thanks for the heads-up!

**Comment by deathwaltz** [comment]
Hi, I can confirm it works. Thanks!
